### ISSUE TITLE
Enable googleanalytics only after clicking close/ok

### ISSUE THREAD

**Issue by fourroses666** [AshleyDawson/cookiepolicy#1]
Hi Ashley, is it correct when paste Google Analytics code between the on close funtion it adds the g.a. cookie on clicking the close button?

`on_closed: function() { .. ga code .. }`

**Comment by fourroses666** [comment]
I don't understand the callback, when I place the googleanalytics in one of the callback functions the googleanalytics cookie isn't set.

**Comment by AshleyDawson** [comment]
Hi @fourroses666 - thanks for your question. 

I've been running this script in production for a large client for a number of years now without it affecting other cookies.

It's a strange effect that you're seeing there as the on_close callback simply runs arbitrary code when the close button is clicked.

In the mean time, if you're concerned about the operation of this jQuery plugin I would suggest using another script, such as: http://cookiecuttr.com/

I'll be looking at this issue as soon as I have a spare moment.

**Comment by fourroses666** [comment]
Thanks for your reply!
Its not a big priority on my side but really like this one.
I need to have a couple of other tests, perhaps the jquery version is a problem I dunno I'm not really a good coder. Will try on a clean page aswell.

At the moment it just don't seem to add a g.a. cookie when adding it into one of the callbacks.

**Comment by AshleyDawson** [comment]
I have a feeling it may be the code at: https://github.com/AshleyDawson/cookiepolicy/blob/master/cookiepolicy.jquery.js#L20

This is where the cookie for the plugin is set.

I'll post on here once I've looked at it and have managed to replicate your issue.

Thanks for your interest in this plugin!

**Comment by fourroses666** [comment]
made a blank testpage here:
http://tinyurl.com/qbqsjtr

doesn't seem to add the ga. cookie. :hand: 
when going to the homepage which isn't using the script the cookie is added. :+1: 

I guess its somewhere in the code :cold_sweat:

**Comment by AshleyDawson** [comment]
@fourroses666 thanks for setting that up - I'll be looking at the issue within the next few days. I will keep you posted.

**Comment by fourroses666** [comment]
sounds cool with me, I'm in no hurry.

ps. I did see some weird stuff going on when changing the message: 
`'This is overriding the message. It's ...` 

then I'm getting a double message.
The ' in `It's` isn't correct. Breaks the line if you know what I mean.

**Comment by fourroses666** [comment]
Hey Ashley, maybe the problem with googleanalytics is these double function calls?
The google analytics cookie doesn't get saved.

`, on_closed: function() {
                    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                        (i[r].q=i[.... more code
                    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
                    ga('create', 'UA-25298xxx-xx', 'auto');
                    ga('send', 'pageview');
                }`

**Comment by AshleyDawson** [comment]
Hi @fourroses666,

Sorry about the late reply! I've been super busy this week.

Just to let you know I'll be looking at the issue today :)

**Comment by AshleyDawson** [comment]
Hi @fourroses666 

I've ran various tests on a correctly functioning version of your code:

(In this example, no cookies are dropped or modified)

``` html
<!doctype html>
<html lang="nl">
    <head>
        <meta charset="UTF-8">
        <title>test</title>
        <script src="http://code.jquery.com/jquery-1.11.1.js"></script>

        <link href="cookiepolicy.jquery.css" media="screen" rel="stylesheet" type="text/css" />
        <script src="cookiepolicy.jquery.js"></script>

    </head>
    <body>

        <h1>TEST</h1>

        <!-- ... -->

        <script>
            (function ($) {
                $('body').cookiepolicy();
            })(jQuery);
        </script>

        <script>
            (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
                    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
            })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
            ga('create', 'UA-7465659-3', 'auto');
            ga('send', 'pageview');
        </script>

    </body>
</html>
```

Please note the changes I've made.

The cookie policy plugin works be displaying a message that the user can hide. It was not designed to embed the Google Analytics code when you hide the cookie policy message.

**Comment by fourroses666** [comment]
Arghhh, seems my trackingcode doesn't work at all omg. Probably because I use a sub URL.
Need to recheck tomorrow. But if this script doesn't works on the g.a. code I think I need to reach for the cookiecuttr script. The popup works fine but it needs to hold the ga script till clicking the close button :(
